export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const REDIS_CLIENT = 'REDIS_CLIENT';
export const AUTH_REPOSITORY = 'AUTH_REPOSITORY';
export const NODEMAILER_SERVICE = 'NODEMAILER_SERVICE';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const BRAND_REPOSITORY = 'BRAND_REPOSITORY';
